/*
 *
 * HistoryPage constants
 *
 */

export const GET_TRANSACTION_HISTORY_REQUEST =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_REQUEST';
export const GET_TRANSACTION_HISTORY_SUCCESS =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_ERROR =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_ERROR';

export const GET_CONFIRMATION_FILE_REQUEST =
  'app/HistoryPage/GET_CONFIRMATION_FILE_REQUEST';
export const GET_CONFIRMATION_FILE_SUCCESS =
  'app/HistoryPage/GET_CONFIRMATION_FILE_SUCCESS';
export const GET_CONFIRMATION_FILE_ERROR =
  'app/HistoryPage/GET_CONFIRMATION_FILE_ERROR';
