/*
 *
 * HistoryPage constants
 *
 */

export const GET_TRANSACTION_HISTORY_REQUEST =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_REQUEST';
export const GET_TRANSACTION_HISTORY_SUCCESS =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_ERROR =
  'app/HistoryPage/GET_TRANSACTION_HISTORY_ERROR';
