/*
 *
 * PaymentPage constants
 *
 */

export const GET_BILLS_REQUEST = 'app/PaymentPage/GET_BILLS_REQUEST';
export const GET_BILLS_SUCCESS = 'app/PaymentPage/GET_BILLS_SUCCESS';
export const GET_BILLS_ERROR = 'app/PaymentPage/GET_BILLS_ERROR';

export const SEARCH_RECIPIENT_REQUEST =
  'app/PaymentPage/SEARCH_RECIPIENT_REQUEST';
export const SEARCH_RECIPIENT_SUCCESS =
  'app/PaymentPage/SEARCH_RECIPIENT_SUCCESS';
export const SEARCH_RECIPIENT_ERROR = 'app/PaymentPage/SEARCH_RECIPIENT_ERROR';

export const CHECK_RECIPIENT = 'app/PaymentPage/CHECK_RECIPIENT';
export const CHECK_RECIPIENT_CORRECT =
  'app/PaymentPage/CHECK_RECIPIENT_CORRECT';
export const CHECK_RECIPIENT_INCORRECT =
  'app/PaymentPage/CHECK_RECIPIENT_INCORRECT';

export const CREATE_TRANSACTION_REQUEST =
  'app/PaymentPage/CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS =
  'app/PaymentPage/CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_ERROR =
  'app/PaymentPage/CREATE_TRANSACTION_ERROR';

export const GET_AUTHORIZATION_KEY_REQUEST =
  'app/PaymentPage/GET_AUTHORIZATION_KEY_REQUEST';
export const GET_AUTHORIZATION_KEY_SUCCESS =
  'app/PaymentPage/GET_AUTHORIZATION_KEY_SUCCESS';
export const GET_AUTHORIZATION_KEY_ERROR =
  'app/PaymentPage/GET_AUTHORIZATION_KEY_ERROR';

export const CONFIRM_TRANSACTION_REQUEST =
  'app/PaymentPage/CONFIRM_TRANSACTION_REQUEST';
export const CONFIRM_TRANSACTION_SUCCESS =
  'app/PaymentPage/CONFIRM_TRANSACTION_SUCCESS';
export const CONFIRM_TRANSACTION_ERROR =
  'app/PaymentPage/CONFIRM_TRANSACTION_ERROR';

export const CHANGE_INPUT = 'app/PaymentPage/CHANGE_INPUT';
export const CHANGE_INPUT_NUMBER = 'app/PaymentPage/CHANGE_INPUT_NUMBER';
export const SELECT_SENDER_BILL = 'app/PaymentPage/SELECT_SENDER_BILL';

export const NEXT_STEP = 'app/PaymentPage/NEXT_STEP';
export const PREVIOUS_STEP = 'app/PaymentPage/PREVIOUS_STEP';
